# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b8bc7bb3b8a4a4b415df32d55604d0dcf4235f3f9b5f50d3fcae1d14f7d2b6cb160374e6d2fd020c8f037a4c5e9927b2cbdd531a2fc1d7b829a741368c0a70e

test:
  secret_key_base: 25cb2d9d5e371cab4eeb63c04e4f8981e7c7aa573be230ec141257a4b9d432e8045a5e64414752941a31acf506b0a1be36a80f0cc41e22655cddf3b9b803a8c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
